name: GitHub Actions Demo
on: push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: |
          echo "a=something" >> $GITHUB_OUTPUT
          echo "b=" >> $GITHUB_OUTPUT
        id: something

      - run: echo a
        if: ${{ steps.something.a != '' }}
      - run: echo b
        if: ${{ steps.something.b != '' }}

