name: GitHub Actions Demo
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: jq -e ".a == 1" test.json

      - run: jq -e ".b == 5" test.json
      - run: |
          curl --request POST --url https://api.github.com/repos/${{ github.repository }}/check-runs \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type:application/vnd.github.v3+json' \
            --data '{
              "name": "test-something",
              "head_sha": "${{ github.event.pull_request.head.sha }}",
              "conclusion": "success",
              "output": {
                "title": "test title",
                "summary": "sometimes this is good",
                "text": "this is what the text looks like"
              }
              }'

