name: GitHub Actions Demo
on:
  push:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: |
          echo "a=something" >> $GITHUB_OUTPUT
          echo "b=" >> $GITHUB_OUTPUT
        id: something
      - run: echo is_scheduled
        if: ${{ github.event.schedule != '' }}

      - run: echo a
        if: ${{ steps.something.outputs.a != '' }}
      - run: echo b
        if: ${{ steps.something.outputs.b != '' }}

